version: '3'
services:
  acedatacloud-studio-frontend:
    container_name: 'acedatacloud-studio-frontend'
    build: ./
    image: 'ghcr.io/acedatacloud/studio-frontend:${BUILD_NUMBER}'
    ports:
      - '8080:80'
