import {
  CHAT_MODEL_ICON_CHATGPT,
  CHAT_MODEL_ICON_CLAUDE,
  CHAT_MODEL_ICON_DEEPSEEK,
  CHAT_MODEL_ICON_GEMINI,
  CHAT_MODEL_ICON_GROK,
  CHAT_MODEL_ICON_KIMI,
  CODING_BRIDGE_LOGO,
  DIGITALHUMAN_LOGO,
  FISH_LOGO,
  FLUX_LOGO,
  GROKVIDEO_LOGO,
  HAILUO_LOGO,
  KLING_LOGO,
  LUMA_LOGO,
  MAESTRO_LOGO,
  MIDJOURNEY_LOGO,
  NANOBANANA_LOGO,
  OMNI_LOGO,
  OPENAIIMAGE_LOGO,
  PIKA_LOGO,
  PIXVERSE_LOGO,
  PRODUCER_LOGO,
  QRART_LOGO,
  SEEDANCE_LOGO,
  SEEDREAM_LOGO,
  SERP_LOGO,
  SORA_LOGO,
  SUNO_LOGO,
  VEO_LOGO,
  WAN_LOGO,
  WEBEXTRATOR_LOGO
} from '@/constants';

export const CAPABILITY_KEYS = [
  'chatgpt',
  'grok',
  'gemini',
  'claude',
  'deepseek',
  'midjourney',
  'qrart',
  'suno',
  'luma',
  'pika',
  'kling',
  'veo',
  'sora',
  'pixverse',
  'flux',
  'hailuo',
  'nanobanana',
  'openaiimage',
  'seedream',
  'seedance',
  'omni',
  'grokvideo',
  'maestro',
  'digitalhuman',
  'wan',
  'producer',
  'kimi',
  'serp',
  'fish',
  'webextrator',
  'codingBridge'
] as const;

export type CapabilityKey = (typeof CAPABILITY_KEYS)[number];

export const CAPABILITY_ICONS: Record<CapabilityKey, string> = {
  chatgpt: CHAT_MODEL_ICON_CHATGPT,
  grok: CHAT_MODEL_ICON_GROK,
  gemini: CHAT_MODEL_ICON_GEMINI,
  claude: CHAT_MODEL_ICON_CLAUDE,
  deepseek: CHAT_MODEL_ICON_DEEPSEEK,
  midjourney: MIDJOURNEY_LOGO,
  qrart: QRART_LOGO,
  suno: SUNO_LOGO,
  luma: LUMA_LOGO,
  pika: PIKA_LOGO,
  kling: KLING_LOGO,
  veo: VEO_LOGO,
  sora: SORA_LOGO,
  pixverse: PIXVERSE_LOGO,
  flux: FLUX_LOGO,
  hailuo: HAILUO_LOGO,
  nanobanana: NANOBANANA_LOGO,
  openaiimage: OPENAIIMAGE_LOGO,
  seedream: SEEDREAM_LOGO,
  seedance: SEEDANCE_LOGO,
  omni: OMNI_LOGO,
  grokvideo: GROKVIDEO_LOGO,
  maestro: MAESTRO_LOGO,
  digitalhuman: DIGITALHUMAN_LOGO,
  wan: WAN_LOGO,
  producer: PRODUCER_LOGO,
  kimi: CHAT_MODEL_ICON_KIMI,
  serp: SERP_LOGO,
  fish: FISH_LOGO,
  webextrator: WEBEXTRATOR_LOGO,
  codingBridge: CODING_BRIDGE_LOGO
};
