export const MIDJOURNEY_MODE_NAME_FAST = 'fast';
export const MIDJOURNEY_MODE_NAME_RELAX = 'relax';
export const MIDJOURNEY_MODE_NAME_TURBO = 'turbo';

export const MIDJOURNEY_SERVICE_ID = 'd87e5e99-b797-4ade-9e73-b896896b0461';

export const MIDJOURNEY_DEFAULT_RATIO = '1:1';
export const MIDJOURNEY_DEFAULT_IMAGE_WEIGHT = 1.0;
export const MIDJOURNEY_DEFAULT_STYLIZE = 100;
export const MIDJOURNEY_DEFAULT_WIRED = 0;
export const MIDJOURNEY_DEFAULT_MODE = MIDJOURNEY_MODE_NAME_FAST;
export const MIDJOURNEY_DEFAULT_QUALITY = '1';
